### ISSUE TITLE
Bad dates and articles association in sento_corpus() when giving a data.frame not pre-sorted by dates

### ISSUE THREAD

**Issue by keblu** [SentometricsResearch/sentometrics#15]
When giving a data.frame as input for sento_corpus() with the date not pre-sorted, the sento_corpus function output the corpus with the dates sorted, but the text does not follow.

As such, the first text of the original data.frame is given the earliest date in sento_corpus, even though this is not its date of publication.

**Comment by sborms** [comment]
This should have been fixed in the last version from a few months back. Did you upgrade the package? If the issue persists, let me know. :-)
