### ISSUE TITLE
compute_sentiment result text order

### ISSUE THREAD

**Issue by waynelapierre** [SentometricsResearch/sentometrics#19]
When I supply a vector of texts to the compute_sentiment function, the resulted sentiment score data.table has the first column id containing contents like "text1", "text2", etc. 

I would like to confirm that "text1" corresponds to the first element in the text vector, and "text2" corresponds to the second element. I am asking because I need to use the cbind function to combine the text vector with the sentiment score, and I want to make sure the original order is retained.

**Comment by sborms** [comment]
Yes, correct.

You can also transform the texts into a corpus object and specify the ids yourself (you could then merge on them). See here for examples: https://sentometrics-research.com/sentometrics/articles/examples/sentiment.html. Make sure you downloaded the latest version (v0.8.3).

Let me know if you have other questions.
