### ISSUE TITLE
interpretation of sentiment score

### ISSUE THREAD

**Issue by waynelapierre** [SentometricsResearch/sentometrics#20]
This may be a silly question. After reading the manual, I could not figure out how to interpret the sentiment score calculated using the compute_sentiment function. My understanding is that a higher sentiment score means more positive sentiment and a lower sentiment score means more negative sentiment. Is my understanding correct? Thanks.

**Comment by sborms** [comment]
That is indeed a correct basic interpretation - considering the words with a positive (negative) score in your input lexicon typically reflect positive (negative) sentiment. For more details you could read the vignette (https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3067734).
