### ISSUE TITLE
Unnecessary NULL assignment

### ISSUE THREAD

**Issue by koheiw** [SentometricsResearch/sentometrics#4]
**quanteda** v2.0 will introduce a new corpus object, whose underlying object is a character vector. We [checked reverse dependency](https://github.com/quanteda/quanteda/issues/1587) and noticed that the code in your package destroys the object by assigning  `NULL`: 

The solution is only to delete the two lines of code:

https://github.com/sborms/sentometrics/blob/e7484f414acc579ded1097856adb5388a9dcf443/R/sentocorpus.R#L104

https://github.com/sborms/sentometrics/blob/e7484f414acc579ded1097856adb5388a9dcf443/R/sentocorpus.R#L125

We are happy to issue a PR if that is easier for you.

**Comment by sborms** [comment]
Thanks for letting us know. When is the v2.0 planned to be released?

**Comment by koheiw** [comment]
End of May, but could be earlier. 

https://github.com/quanteda/quanteda/milestone/6

**Comment by sborms** [comment]
Thanks, should be taken care of by then.

**Comment by sborms** [comment]
See further: https://github.com/quanteda/quanteda/issues/1587#issuecomment-463469877.

**Comment by sborms** [comment]
See merged pull https://github.com/sborms/sentometrics/pull/5.
