### ISSUE TITLE
sento_corpus format breaks with forthcoming quanteda v2

### ISSUE THREAD

**Issue by kbenoit** [SentometricsResearch/sentometrics#8]
In forthcoming **quanteda** v2, we have redefined the corpus object structure to be a character vector with special attributes, which breaks these functions for your extension of the older pre v2 corpus structure in **sentometrics**. See https://github.com/quanteda/quanteda/issues/1782.

I started fixing your code in a branch from my fork, but realized that this involves some design decisions to your package and that the changes run deeper than a simple compatibility fix.

We could add a conversion function to get an old format of corpus, but then the new v2 `corpus_*()` functions would no longer work with your object class.

Happy to help once you decide on the best fix.

**Comment by sborms** [comment]
Hi Ken,

Thanks for letting me know. I am working on it and should be fine.

Only the `corpus_sample()` function does a bit annoying. It converts my `sento_corpus` object back to a `corpus` object. The other `corpus_*()` functions don't seem to do this (I have a test for this now in `test_corpus_building.R`).

I have an `as.sento_corpus.corpus()` function so there is a way around for users, or I could make a two-line sampling function myself. It would just be a shame that one `corpus_*()` function doesn't do as expected...

A fix might be easy though: can't you just replace the last line [here](https://github.com/quanteda/quanteda/blob/master/R/corpus_sample.R) by `x[i]`? It keeps the input `x` intact and does the sampling as expected.

**Comment by kbenoit** [comment]
Thanks, good suggestion. I’ll work on this asap.

**Comment by sborms** [comment]
Thanks for the changes! This should be OK now. I will recheck again mid-January after CRAN's holiday when I submit sentometrics v0.8.
